name: Antigravity CI Pipeline

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: "Stage 1: Setup Infrastructure (MinIO)"
        run: |
          pip install podman-compose
          podman-compose up -d
          chmod +x setup_buckets.sh
          ./setup_buckets.sh

      - name: "Stage 2: Build ETL Container (Dependencies)"
        run: |
          podman build -t antigravity-etl .

      - name: "Stage 3: Run E2E Pipeline (Generate Data -> dbt Run/Test)"
        run: |
          podman run --rm --network host -v ${{ github.workspace }}:/app antigravity-etl bash -c "python scripts/generate_faker_data.py && dbt run --profiles-dir . && echo -e '\n--- AMOSTRA DOS DADOS (STAGING) ---' && dbt show --select stg_raw_data --profiles-dir . --limit 5 && echo -e '\n--- AMOSTRA DOS DADOS (CURATED) ---' && dbt show --select fct_analytics --profiles-dir . --limit 5 && dbt test --profiles-dir ."
        env:
          MINIO_URL: "http://localhost:9000"

      - name: "End: Teardown Infrastructure"
        if: always()
        run: |
          podman-compose down
